models:
  - type: main
    engine: openai
    model: gemini-3.6-flash
    parameters:
      base_url: "https://generativelanguage.googleapis.com/v1beta/openai/"

rails:
  input:
    flows:
      - self check input